services:
  users-api:
    ports: []

  catalog-api:
    ports: []

  payments-api:
    ports: []

  notifications-api:
    ports: []

  api-gateway:
    build:
      context: ../fcg-api-gateway/Fcg.ApiGateway
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
    depends_on:
      - users-api
      - catalog-api
      - payments-api
      - notifications-api
    ports:
      - "8080:8080"
    networks:
      - fcg
